import os

translations = {
    'en': {
        '<title>Location Voilier': '<title>Sailboat Rental',
        'Lac de Neuchâtel, Suisse': 'Lake of Neuchâtel, Switzerland',
        'Voilier <span>Lac de Neuchâtel</span>': 'Sailboat <span>Lake of Neuchâtel</span>',
        '>Le Bateau<': '>The Boat<',
        '>Tarifs<': '>Rates<',
        '>Pass Skipper<': '>Skipper Pass<',
        '>Infos<': '>Info<',
        '>Avis<': '>Reviews<',
        '>Localisation<': '>Map<',
        '>Réservation<': '>Book Now<',
        'Location voilier': 'Sailboat rental',
        'Port de Cheyres · Lac de Neuchâtel · Suisse': 'Cheyres Harbour · Lake of Neuchâtel · Switzerland',
        'Votre voilier sur le <em>lac de Neuchâtel</em>': 'Your sailboat on <em>Lake of Neuchâtel</em>',
        'Partez à l\'aventure sur les eaux turquoises du lac de Neuchâtel, ses bancs de sable et sa réserve naturelle préservée.': 'Set sail on the turquoise waters of Lake of Neuchâtel, discover its sandbars and preserved nature reserve.',
        'avis vérifiés': 'verified reviews',
        '>Découvrir le bateau<': '>Discover the boat<',
        '>Voir les tarifs<': '>View rates<',
        'Le bateau': 'The Boat',
        'First 210 Spirit — <em>Rapide & Sûr</em>': 'First 210 Spirit — <em>Fast & Safe</em>',
        'Le Bénéteau First 210 est le croiseur côtier par excellence.': 'The Bénéteau First 210 is the ultimate coastal cruiser.',
        'Insoumersible, grand cockpit, très marin et facile à manœuvrer.': 'Unsinkable, large cockpit, very seaworthy and easy to handle.',
        '>Longueur<': '>Length<',
        '>Largeur<': '>Beam<',
        '>Tirant d\'eau<': '>Draft<',
        'quille relevable': 'lifting keel',
        '>Voilure<': '>Sail area<',
        'Grand-voile & foc sur enrouleur': 'Mainsail & furling jib',
        '>Moteur<': '>Engine<',
        'Hors-bord 5cv 4T': 'Outboard 5hp 4-stroke',
        '>Capacité<': '>Capacity<',
        '4 personnes max': '4 persons max',
        'Moteur 4 Temps récent': 'Recent 4-stroke engine',
        'Cabine 4 couchettes': 'Cabin with 4 berths',
        'Equipement de sécurité complet': 'Full safety equipment',
        'Le permis lac Suisse ou international reconnu est obligatoire.': 'Swiss or recognized international lake permit is required.',
        'Grille tarifaire': 'Pricing',
        'Plus vous naviguez, <em>moins vous payez</em>': 'The more you sail, <em>the less you pay</em>',
        'Mois': 'Month',
        'Jours de semaine uniquement (hors jours fériés suisses) · Réservation selon disponibilité': 'Weekdays only (excluding Swiss public holidays) · Booking subject to availability',
        'Informations pratiques': 'Practical Info',
        'Tout ce qu\'il faut <em>savoir</em>': 'Everything you need to <em>know</em>',
        'Prise en main': 'Handover',
        'Briefing inclus avant chaque départ.': 'Briefing included before each departure.',
        'Permis requis': 'Permit required',
        'Caution': 'Deposit',
        'Caution bloquée par empreinte de carte. Libérée automatiquement au retour sans dommage.': 'Deposit blocked by credit card imprint. Automatically released upon safe return.',
        'Accès': 'Access',
        'Port de Cheyres. Parking payant sur place. Gare de Cheyres-Châbles (ligne Lausanne–Berne).': 'Cheyres harbour. Paid parking on site. Cheyres-Châbles train station (Lausanne–Bern line).',
        'Météo & annulation': 'Weather & cancellation',
        'Remboursement intégral si météo défavorable.': 'Full refund in case of bad weather.',
        'Nuitées port de Cheyres': 'Nights at Cheyres harbour',
        'Nuitées au port de Cheyres gratuites. Restaurant, douches et plage à proximité.': 'Free nights at Cheyres harbour. Restaurant, showers and beach nearby.',
        'Avis clients': 'Customer Reviews',
        'Ce que disent <em>nos locataires</em>': 'What our <em>renters say</em>',
        'Très bonne expérience sur le bateau ! Nous avons fait une super sortie à refaire !': 'Great experience on the boat! We had a wonderful trip, will do it again!',
        'Super petit bateau en très bon état avec des voiles au top. Très bon accueil et explications. Zone de navigation sympa !': 'Great small boat in very good condition with top sails. Great welcome and explanations. Nice sailing area!',
        'Note parfaite sur toutes les catégories': 'Perfect rating in all categories',
        'Le lac de Neuchâtel, <em>votre terrain de jeu</em>': 'Lake of Neuchâtel, <em>your playground</em>',
        'Le plus grand lac entièrement suisse — 38 km de long, eaux turquoises, Alpes en toile de fond. Réputé pour ses belles brises régulières, c\'est l\'un des plans d\'eau les plus agréables pour la voile en Suisse. Le bateau est amarré au port de Cheyres.': 'The largest entirely Swiss lake — 38 km long, turquoise waters, Alps in the background. Known for its beautiful and steady breezes, it\'s one of the most pleasant lakes for sailing in Switzerland. The boat is moored at Cheyres harbor.',
        'Port de Cheyres — accès & parking': 'Cheyres Harbour — access & parking',
        '45 min depuis Lausanne · 30 min depuis Fribourg · 40 min depuis Berne': '45 min from Lausanne · 30 min from Fribourg · 40 min from Bern',
        'Parking payant à proximité du port': 'Paid parking near the harbour',
        'Gare de Cheyres-Châbles (ligne Lausanne–Berne)': 'Cheyres-Châbles train station (Lausanne–Bern line)',
        'Réservation directe': 'Direct Booking',
        'Réservez & <em>payez en ligne</em>': 'Book & <em>pay online</em>',
        'Carburant inclus · Nuitées au port de Cheyres gratuites': 'Fuel included · Free nights at Cheyres harbour',
        'Demande de réservation': 'Reservation Request',
        'Carburant inclus · Nuitées au port de Cheyres gratuites · Caution par empreinte bancaire': 'Fuel included · Free nights at Cheyres harbour · Security deposit via credit card imprint',
        'Choisir la date de départ': 'Choose departure date',
        'Choisir la date de retour': 'Choose return date',
        'Prénom & Nom': 'First & Last Name',
        'Type de réservation': 'Reservation type',
        'Location standard': 'Standard rental',
        'Pass Skipper': 'Skipper Pass',
        '5 jours · semaine · selon disponibilité · année en cours': '5 days · weekdays · upon availability · current year',
        'paiement intégral': 'full payment',
        'Le paiement intégral de 800 CHF est demandé à la souscription. Vous pouvez ensuite réserver vos 5 jours tout au long de l\'année selon disponibilité (jours de semaine hors jours fériés).': 'The full payment of 800 CHF is required upon subscription. You can then book your 5 days throughout the year depending on availability (weekdays excluding public holidays).',
        'Options': 'Options',
        'CHF au total': 'CHF total',
        'Annulation gratuite': 'Free cancellation',
        'si météo défavorable': 'if bad weather',
        'Toutes taxes incluses. Vous ne payez rien aujourd\'hui.': 'All taxes included. You pay nothing today.',
        'Envoyer la demande': 'Send Request',
        'Contact rapide par WhatsApp': 'Quick contact via WhatsApp',
        'Navigation rapide': 'Quick Links',
        'Langues': 'Languages',
        'Français': 'French',
        'Allemand': 'German',
        'Anglais': 'English',
        'Tous droits réservés.': 'All rights reserved.'
    },
    'de': {
        '<title>Location Voilier': '<title>Segelboot Mieten',
        'Lac de Neuchâtel, Suisse': 'Neuenburgersee, Schweiz',
        'Voilier <span>Lac de Neuchâtel</span>': 'Segelboot <span>Neuenburgersee</span>',
        '>Le Bateau<': '>Das Boot<',
        '>Tarifs<': '>Preise<',
        '>Pass Skipper<': '>Skipper Pass<',
        '>Infos<': '>Infos<',
        '>Avis<': '>Bewertungen<',
        '>Localisation<': '>Karte<',
        '>Réservation<': '>Buchen<',
        'Location voilier': 'Segelboot mieten',
        'Port de Cheyres · Lac de Neuchâtel · Suisse': 'Hafen Cheyres · Neuenburgersee · Schweiz',
        'Votre voilier sur le <em>lac de Neuchâtel</em>': 'Ihr Segelboot auf dem <em>Neuenburgersee</em>',
        'Partez à l\'aventure sur les eaux turquoises du lac de Neuchâtel, ses bancs de sable et sa réserve naturelle préservée.': 'Entdecken Sie die türkisfarbenen Gewässer des Neuenburgersees, seine Sandbänke und das intakte Naturschutzgebiet.',
        'avis vérifiés': 'verifizierte Bewertungen',
        '>Découvrir le bateau<': '>Das Boot entdecken<',
        '>Voir les tarifs<': '>Preise ansehen<',
        'Le bateau': 'Das Boot',
        'First 210 Spirit — <em>Rapide & Sûr</em>': 'First 210 Spirit — <em>Schnell & Sicher</em>',
        'Le Bénéteau First 210 est le croiseur côtier par excellence.': 'Die Bénéteau First 210 ist der perfekte Küstenkreuzer.',
        'Insoumersible, grand cockpit, très marin et facile à manœuvrer.': 'Unsinkbar, großes Cockpit, sehr seetüchtig und leicht zu manövrieren.',
        '>Longueur<': '>Länge<',
        '>Largeur<': '>Breite<',
        '>Tirant d\'eau<': '>Tiefgang<',
        'quille relevable': 'Hubkiel',
        '>Voilure<': '>Segelfläche<',
        'Grand-voile & foc sur enrouleur': 'Großsegel & Rollfock',
        '>Moteur<': '>Motor<',
        'Hors-bord 5cv 4T': 'Außenborder 5PS 4-Takt',
        '>Capacité<': '>Kapazität<',
        '4 personnes max': 'Max 4 Personen',
        'Moteur 4 Temps récent': 'Neuer 4-Takt-Motor',
        'Cabine 4 couchettes': 'Kabine mit 4 Kojen',
        'Equipement de sécurité complet': 'Komplette Sicherheitsausrüstung',
        'Le permis lac Suisse ou international reconnu est obligatoire.': 'Ein Schweizer oder anerkannter internationaler Binnenschein ist erforderlich.',
        'Grille tarifaire': 'Preise',
        'Plus vous naviguez, <em>moins vous payez</em>': 'Je mehr Sie segeln, <em>desto weniger zahlen Sie</em>',
        'Mois': 'Monat',
        'Jours de semaine uniquement (hors jours fériés suisses) · Réservation selon disponibilité': 'Nur wochentags (außer an Schweizer Feiertagen) · Buchung nach Verfügbarkeit',
        'Informations pratiques': 'Praktische Infos',
        'Tout ce qu\'il faut <em>savoir</em>': 'Alles was Sie <em>wissen</em> müssen',
        'Prise en main': 'Übergabe',
        'Briefing inclus avant chaque départ.': 'Briefing vor jeder Abfahrt inklusive.',
        'Permis requis': 'Führerschein erforderlich',
        'Caution': 'Kaution',
        'Caution bloquée par empreinte de carte. Libérée automatiquement au retour sans dommage.': 'Kaution per Kreditkartenabzug blockiert. Wird bei schadenfreier Rückkehr automatisch freigegeben.',
        'Accès': 'Anreise',
        'Port de Cheyres. Parking payant sur place. Gare de Cheyres-Châbles (ligne Lausanne–Berne).': 'Hafen Cheyres. Kostenpflichtiger Parkplatz vor Ort. Bahnhof Cheyres-Châbles (Linie Lausanne–Bern).',
        'Météo & annulation': 'Wetter & Stornierung',
        'Remboursement intégral si météo défavorable.': 'Volle Rückerstattung bei schlechtem Wetter.',
        'Nuitées port de Cheyres': 'Übernachtungen im Hafen Cheyres',
        'Nuitées au port de Cheyres gratuites. Restaurant, douches et plage à proximité.': 'Kostenlose Übernachtungen im Hafen Cheyres. Restaurant, Duschen und Strand in der Nähe.',
        'Avis clients': 'Kundenbewertungen',
        'Ce que disent <em>nos locataires</em>': 'Was unsere <em>Kunden sagen</em>',
        'Très bonne expérience sur le bateau ! Nous avons fait une super sortie à refaire !': 'Sehr gute Erfahrung auf dem Boot! Wir hatten einen tollen Ausflug, gerne wieder!',
        'Super petit bateau en très bon état avec des voiles au top. Très bon accueil et explications. Zone de navigation sympa !': 'Tolles kleines Boot in sehr gutem Zustand mit Top-Segeln. Sehr guter Empfang und Erklärungen. Schönes Segelrevier!',
        'Note parfaite sur toutes les catégories': 'Perfekte Bewertung in allen Kategorien',
        'Le lac de Neuchâtel, <em>votre terrain de jeu</em>': 'Der Neuenburgersee, <em>Ihr Spielplatz</em>',
        'Le plus grand lac entièrement suisse — 38 km de long, eaux turquoises, Alpes en toile de fond. Réputé pour ses belles brises régulières, c\'est l\'un des plans d\'eau les plus agréables pour la voile en Suisse. Le bateau est amarré au port de Cheyres.': 'Der größte vollständig in der Schweiz liegende See — 38 km lang, türkisfarbenes Wasser, Alpen im Hintergrund. Bekannt für seine schönen, gleichmäßigen Winde, ist er eines der angenehmsten Segelreviere der Schweiz. Das Boot liegt im Hafen von Cheyres.',
        'Port de Cheyres — accès & parking': 'Hafen Cheyres — Anreise & Parken',
        '45 min depuis Lausanne · 30 min depuis Fribourg · 40 min depuis Berne': '45 Min. von Lausanne · 30 Min. von Freiburg · 40 Min. von Bern',
        'Parking payant à proximité du port': 'Kostenpflichtige Parkplätze in der Nähe des Hafens',
        'Gare de Cheyres-Châbles (ligne Lausanne–Berne)': 'Bahnhof Cheyres-Châbles (Linie Lausanne–Bern)',
        'Réservation directe': 'Direktbuchung',
        'Réservez & <em>payez en ligne</em>': 'Buchen & <em>online bezahlen</em>',
        'Carburant inclus · Nuitées au port de Cheyres gratuites': 'Treibstoff inklusive · Kostenlose Nächte im Hafen Cheyres',
        'Demande de réservation': 'Buchungsanfrage',
        'Carburant inclus · Nuitées au port de Cheyres gratuites · Caution par empreinte bancaire': 'Treibstoff inklusive · Kostenlose Nächte im Hafen Cheyres · Kaution per Kreditkartenabzug',
        'Choisir la date de départ': 'Abfahrtsdatum wählen',
        'Choisir la date de retour': 'Rückgabedatum wählen',
        'Prénom & Nom': 'Vorname & Nachname',
        'Type de réservation': 'Buchungstyp',
        'Location standard': 'Standardmiete',
        'Pass Skipper': 'Skipper Pass',
        '5 jours · semaine · selon disponibilité · année en cours': '5 Tage · Wochentags · nach Verfügbarkeit · laufendes Jahr',
        'paiement intégral': 'Vollständige Bezahlung',
        'Le paiement intégral de 800 CHF est demandé à la souscription. Vous pouvez ensuite réserver vos 5 jours tout au long de l\'année selon disponibilité (jours de semaine hors jours fériés).': 'Die vollständige Zahlung von 800 CHF ist bei Vertragsabschluss fällig. Sie können Ihre 5 Tage dann je nach Verfügbarkeit das ganze Jahr über buchen (wochentags außer an Feiertagen).',
        'Options': 'Optionen',
        'CHF au total': 'CHF insgesamt',
        'Annulation gratuite': 'Kostenlose Stornierung',
        'si météo défavorable': 'bei schlechtem Wetter',
        'Toutes taxes incluses. Vous ne payez rien aujourd\'hui.': 'Alle Steuern inbegriffen. Sie zahlen heute nichts.',
        'Envoyer la demande': 'Anfrage senden',
        'Contact rapide par WhatsApp': 'Schneller Kontakt über WhatsApp',
        'Navigation rapide': 'Schnellnavigation',
        'Langues': 'Sprachen',
        'Français': 'Französisch',
        'Allemand': 'Deutsch',
        'Anglais': 'Englisch',
        'Tous droits réservés.': 'Alle Rechte vorbehalten.'
    }
}

title_tags = {
    'en': {
        '<a href="#accueil" class="logo">Voilier <span>Lac de Neuchâtel</span></a>': '<a href="#accueil" class="logo">Sailing <span>Lake of Neuchâtel</span></a>',
        '<a href="#accueil" class="logo">Sailboat <span>Lake of Neuchâtel</span></a>': '<a href="#accueil" class="logo">Sailing <span>Lake of Neuchâtel</span></a>'
    },
    'de': {
        '<a href="#accueil" class="logo">Voilier <span>Lac de Neuchâtel</span></a>': '<a href="#accueil" class="logo">Segeln <span>Neuenburgersee</span></a>',
        '<a href="#accueil" class="logo">Segelboot <span>Neuenburgersee</span></a>': '<a href="#accueil" class="logo">Segeln <span>Neuenburgersee</span></a>'
    }
}

for lang in ['en', 'de']:
    try:
        with open(f"/home/gregory/Voilier/site/{lang}/index.html", "r") as f:
            content = f.read()
        
        # We start with replacing all translations from FR -> Target
        for fr_str, target_str in translations[lang].items():
            content = content.replace(fr_str, target_str)
            
        # specifically fix the navigation Title
        for fr_str, target_str in title_tags[lang].items():
            content = content.replace(fr_str, target_str)
            
        with open(f"/home/gregory/Voilier/site/{lang}/index.html", "w") as f:
            f.write(content)
        print(f"Applied full translations for {lang}")
    except Exception as e:
        print(f"Failed {lang}: {e}")
