import re

def main():
    with open('site/index.html', 'r', encoding='utf-8') as f:
        fr = f.read()

    en_replacements = [
        ('Voilier <span>lac de Neuchâtel</span>', 'Sailboat <span>Lake of Neuchâtel</span>'),
        ('Le bateau', 'The Boat'),
        ('>Tarifs<', '>Rates<'),
        ('Pass Skipper', 'Skipper Pass'),
        ('>Infos<', '>Info<'),
        ('>Avis<', '>Reviews<'),
        ('Carte', 'Map'),
        ('À propos', 'About'),
        ('>Réserver<', '>Book Now<'),
        ('Location de voilier', 'Sailboat Rental'),
        ('Port de Cheyres · Lac de Neuchâtel · Suisse', 'Port of Cheyres · Lake of Neuchâtel · Switzerland'),
        ('<h1>Votre voilier sur le <em>lac de Neuchâtel</em></h1>', '<h1>Your sailboat on the <em>Lake of Neuchâtel</em></h1>'),
        ("Partez à l'aventure sur les eaux turquoises du lac de Neuchâtel, ses bancs de sable et sa réserve naturelle préservée.", "Embark on an adventure on the turquoise waters of Lake Neuchâtel, its sandbanks and its preserved nature reserve."),
        ('5 avis vérifiés', '5 verified reviews'),
        ('Propriétaire vérifié', 'Verified owner'),
        ('Réserver maintenant', 'Book now'),
        ('Découvrir le bateau', 'Discover the boat'),
        ('>Longueur<', '>Length<'),
        ('Personnes max', 'Max people'),
        ('Lits doubles', 'Double beds'),
        ('Note · 5 avis', 'Rating · 5 reviews'),
        ('Nuitées port Cheyres', 'Nights port Cheyres'),
        ('>Le voilier<', '>The Sailboat<'),
        ("Le Maxus 21 est un voilier habitable de 6.5 m, conçu par l'architecte naval Jacek Daszkiewicz et produit par le chantier polonais Northman. Gréé en sloop fractionné avec génois sur enrouleur, grand-voile lattée avec lazy-jack et gennaker, il offre un excellent compromis entre performance et facilité de manœuvre. Sa quille relevable (tirant d'eau de 0.35 à 1.45 m) permet d'accéder aux zones peu profondes et aux plages du lac de Neuchâtel. Le cockpit spacieux accueille confortablement 4 personnes, et la cabine équipée — frigo 12V, réchaud gaz, vaisselle, 2 lits doubles — permet de séjourner plusieurs nuits à bord en autonomie complète. Idéal pour les débutants avec permis comme pour les skippers expérimentés, en solo, en couple ou en famille.", "The Maxus 21 is a 6.5m livable sailboat, designed by naval architect Jacek Daszkiewicz and produced by the Polish shipyard Northman. Rigged as a fractional sloop with a furling genoa, battened mainsail with lazy-jack and gennaker, it offers an excellent compromise between performance and ease of handling. Its lifting keel (draft from 0.35 to 1.45m) allows access to shallow areas and the beaches of Lake Neuchâtel. The spacious cockpit comfortably accommodates 4 people, and the equipped cabin — 12V fridge, gas stove, dishes, 2 double beds — allows for several nights aboard in complete autonomy. Ideal for beginners with a license as well as for experienced skippers, solo, as a couple or with family."),
        ('Équipements et caractéristiques', 'Equipment and features'),
        ('Performances', 'Performance'),
        ('Grand-voile 14m², Génois 9m², Gennaker 23m²', 'Mainsail 14m², Genoa 9m², Gennaker 23m²'),
        ('Moteur hors-bord 5cv 4 temps', '5hp 4-stroke outboard motor'),
        ('Confort à bord', 'Comfort on board'),
        ('2 lits doubles (avant et arrière) pour 4 personnes', '2 double beds (front and rear) for 4 people'),
        ('Réchaud gaz, frigo 12V, vaisselle complète', 'Gas stove, 12V fridge, complete dishes'),
        ('Toilettes chimiques', 'Chemical toilets'),
        ('Pris USB, éclairage LED', 'USB ports, LED lighting'),
        ('Sécurité', 'Security'),
        ('Armement de sécurité complet pour 4 personnes', 'Complete safety equipment for 4 people'),
        ('Bouées, gilets, fusées, extincteur', 'Buoys, life jackets, flares, fire extinguisher'),
        ('>Navigation<', '>Navigation<'),
        ('Tableau électrique, loch, speedo, sondeur, compas', 'Electrical panel, log, speedo, depth sounder, compass'),
        ('Cartes nautiques du lac de Neuchâtel', 'Nautical charts of Lake Neuchâtel'),
        ('Tarifs de <em style="color:var(--lake)">location</em>', 'Rental <em style="color:var(--lake)">Rates</em>'),
        ("Profitez d'un tarif dégressif dès le 2ème jour. Inclus : assurance casco complète et place d'amarrage à Cheyres.", "Enjoy a sliding scale rate from the 2nd day. Included: comprehensive insurance and mooring place in Cheyres."),
        ("Basse saison", "Low season"),
        ("1 avr - 15 juin / 16 sept - 31 oct", "Apr 1 - Jun 15 / Sep 16 - Oct 31"),
        ("Haute saison", "High season"),
        ("16 juin - 15 sept", "Jun 16 - Sep 15"),
        ("Réserver ces dates", "Book these dates"),
        ("Nos options <em>disponibles</em>", "Our <em>available</em> options"),
        ("Personnalisez votre location avec nos options.", "Personalize your rental with our options."),
        ("Moteur électrique", "Electric motor"),
        ("Moteur Torqeedo Travel 1103 CS silencieux, écologique et performant.", "Torqeedo Travel 1103 CS motor, quiet, eco-friendly and high-performance."),
        ("Paddle Board", "Paddle Board"),
        ("SUP gonflable pour explorer les plages et bas-fonds.", "Inflatable SUP to explore beaches and shallows."),
        ("Nuit au port de Cheyres", "Night at Cheyres port"),
        ("Dormez à bord la veille de votre départ, accès aux sanitaires du port inclus.", "Sleep on board the night before your departure, access to port sanitary facilities included."),
        (">Nettoyage<", ">Cleaning<"),
        ("Nettoyage complet intérieur et extérieur après votre location.", "Complete indoor and outdoor cleaning after your rental."),
        ("Faites vous <em>accompagner</em>", "Get <em>accompanied</em>"),
        ("Vous n'avez pas le permis voile marin ? Aucun problème. Avec le Pass Skipper, un skipper expérimenté vous accompagnera pour vous guider lors de votre sortie.", "Don't have a marine sailing license? No problem. With the Skipper Pass, an experienced skipper will accompany you to guide you during your trip."),
        ("Jusqu'à 3 personnes maximum", "Up to 3 people maximum"),
        ("Journée de 9h à 17h : +150 CHF", "Day from 9am to 5pm : +150 CHF"),
        ("Information de <em>location</em>", "Rental <em>information</em>"),
        ("Tout ce qu'il faut savoir avant de larguer les amarres.", "Everything you need to know before casting off."),
        ("Conditions requises", "Requirements"),
        ("Permis voile (catégorie D) obligatoire suisse", "Swiss sailing license (category D) mandatory"),
        ("Âge minimum : 25 ans", "Minimum age: 25 years"),
        ("Caution de 1000 CHF", "1000 CHF deposit"),
        (">Horaires<", ">Schedules<"),
        ("Prise en charge dès 9h00", "Pick-up from 9:00 am"),
        ("Retour jusqu'à 17h00", "Return until 5:00 pm"),
        ("Briefing de 30 min au départ", "30 min briefing at departure"),
        ("Inclus dans le prix", "Included in the price"),
        ("Amarrage au port de Cheyres", "Mooring at the port of Cheyres"),
        ("Assurance casco complète (franchise 1000 CHF)", "Comprehensive casco insurance (1000 CHF deductible)"),
        ("Ceinture de sauvetage automatiques", "Automatic life jackets"),
        ("Équipement de sécurité complet", "Complete safety equipment"),
        ("Vaisselle et matériel de cuisine", "Dishes and cooking utensils"),
        ("Taxe de séjour", "City tax"),
        ("À prévoir", "To bring"),
        ("Sac de couchage et oreiller", "Sleeping bag and pillow"),
        ("Chaussures à semelles claires et propres", "Shoes with clean and light soles"),
        ("Crème solaire respectueuse de l'environnement", "Eco-friendly sunscreen"),
        ("Vêtements de pluie / adaptés à la météo", "Rain gear / weather-appropriate clothing"),
        ("Vos affaires personnelles dans un sac souple idéalement", "Your personal belongings in a soft bag ideally"),
        ('Le lac de Neuchâtel, <em style="color:var(--lake)">votre terrain de jeu</em>', 'Lake of Neuchâtel, <em style="color:var(--lake)">your playground</em>'),
        ("Au départ du charmant port de Cheyres, découvrez la Rive Sud et sa réserve naturelle préservée. Naviguez jusqu'à Estavayer-le-Lac, Yvonand, ou traversez vers Neuchâtel et Grandson. Les plages de sable, les eaux turquoises et les paysages jurassiens vous offrent un cadre de navigation exceptionnel.", "Departing from the charming port of Cheyres, discover the South Shore and its preserved nature reserve. Sail to Estavayer-le-Lac, Yvonand, or cross to Neuchâtel and Grandson. The sandy beaches, turquoise waters, and Jura landscapes offer you an exceptional sailing environment."),
        ("Avis de nos <em>navigateurs</em>", "Reviews from our <em>sailors</em>"),
        ("Laisser un avis", "Leave a review"),
        ("Super journée", "Great day"),
        ("Nous avons passé une journée magnifique sur le Maxus 21. Le bateau est très bien entretenu, facile à manœuvrer et parfait pour une sortie familiale. L'accueil au port de Cheyres était très pro et les conseils de navigation précieux.", "We spent a magnificent day on the Maxus 21. The boat is very well maintained, easy to handle and perfect for a family outing. The welcome at the port of Cheyres was very professional and the navigation advice invaluable."),
        ("Week-end parfait", "Perfect weekend"),
        ("Première expérience de nuit sur le lac de Neuchâtel. La cabine est étonnamment spacieuse pour la taille du bateau. Le frigo et le réchaud fonctionnent parfaitement. Réveil au mouillage devant la réserve naturelle : magique !", "First overnight experience on Lake Neuchâtel. The cabin is surprisingly spacious for the size of the boat. The fridge and stove work perfectly. Waking up at anchor in front of the nature reserve: magical!"),
        ("Idéal pour se remettre à la voile", "Ideal for getting back to sailing"),
        ("N'ayant pas navigué depuis quelques années, le Maxus 21 était le choix parfait. Rassurant, réactif et très fun sous gennaker. Merci pour le briefing détaillé avant le départ.", "Having not sailed for a few years, the Maxus 21 was the perfect choice. Reassuring, responsive and very fun under gennaker. Thank you for the detailed briefing before departure."),
        ('Port de <em>Cheyres</em>', 'Port of <em>Cheyres</em>'),
        ("Notre voilier est amarré au port de Cheyres, sur la rive sud du lac de Neuchâtel. Un point de départ idéal !", "Our sailboat is moored at the port of Cheyres, on the south shore of Lake Neuchâtel. An ideal starting point!"),
        (">Cheyres<", ">Cheyres<"),
        ("Gare CFF à 10 minutes à pied.", "SBB train station 10 minutes on foot."),
        ("Parking gratuit à disposition au nord.", "Free parking available to the north."),
        ("Sanitaires, douches, restaurants.", "Sanitary facilities, showers, restaurants."),
        ('Prêt à <em>embarquer</em> ?', 'Ready to <em>embark</em>?'),
        ("Remplissez le formulaire ci-dessous avec vos dates souhaitées. Nous vous répondrons sous 24h avec une confirmation et les instructions pour le paiement de l'acompte.", "Fill out the form below with your desired dates. We will reply within 24h with a confirmation and instructions for the deposit payment."),
        ("Votre nom", "Your name"),
        ("Votre e-mail", "Your email"),
        ("Numéro de téléphone", "Phone number"),
        ("Jour de départ", "Departure day"),
        ("Jour de retour", "Return day"),
        ("Option de location", "Rental option"),
        ("Je choisis mes options", "I choose my options"),
        (">Aucune<", ">None<"),
        ("Message ou question éventuelle", "Message or possible question"),
        ("Êtes vous prêt pour une confirmation ?", "Are you ready for a confirmation?"),
        (">Oui<", ">Yes<"),
        ("Je l'envoi", "Send"),
        ("Location en demande :", "Rental on request:"),
        ("Votre propriétaire", "Your owner"),
        ("Je m'appelle Grégory, naviguant sur les lacs de Neuchâtel et Bienne depuis toujours. C'est avec plaisir de pouvoir partager mon bateau aujourd'hui.", "My name is Grégory, sailing on the lakes of Neuchâtel and Biel since always. It is a pleasure to be able to share my boat today."),
        ("Voilier situé au", "Sailboat located at"),
        (">Port de Cheyres<", ">Port of Cheyres<"),
        ("Rte du Port", "Port Rd"),
        ("1468 Cheyres", "1468 Cheyres"),
        (">Suisse<", ">Switzerland<"),
        ("Contact & Suivi", "Contact & Follow"),
        ("Partenariat", "Partnership"),
        (">Conditions<", ">Terms<"),
        ("Conditions de location", "Rental conditions"),
        ("Mentions légales", "Legal mentions"),
        ("Tous droits réservés.", "All rights reserved.")
    ]

    en_content = fr
    for old, new in en_replacements:
        en_content = en_content.replace(old, new)
        
    en_content = en_content.replace('lang-active">FR</a> <a href="/de/">DE</a> <a href="/en/">EN',
                                  '">FR</a> <a href="/de/">DE</a> <a href="/en/" class="lang-active">EN')
    en_content = en_content.replace('<html lang="fr">', '<html lang="en">')
    en_content = en_content.replace('<title>Location de Voilier au lac de Neuchâtel | Port de Cheyres</title>', '<title>Sailing Lake of Neuchâtel | Sailboat Rental | Port of Cheyres</title>')
    en_content = en_content.replace('value="Nouvelle demande de réservation (FR)"', 'value="New booking request (EN)"')

    with open('site/en/index.html', 'w', encoding='utf-8') as f:
        f.write(en_content)


    de_replacements = [
        ('Voilier <span>lac de Neuchâtel</span>', 'Segelboot <span>Neuenburgersee</span>'),
        ('Le bateau', 'Das Boot'),
        ('>Tarifs<', '>Preise<'),
        ('Pass Skipper', 'Skipper Pass'),
        ('>Infos<', '>Info<'),
        ('>Avis<', '>Bewertungen<'),
        ('Carte', 'Karte'),
        ('À propos', 'Über uns'),
        ('>Réserver<', '>Buchen<'),
        ('Location de voilier', 'Segelboot Mieten'),
        ('Port de Cheyres · Lac de Neuchâtel · Suisse', 'Hafen von Cheyres · Neuenburgersee · Schweiz'),
        ('<h1>Votre voilier sur le <em>lac de Neuchâtel</em></h1>', '<h1>Ihr Segelboot auf dem <em>Neuenburgersee</em></h1>'),
        ("Partez à l'aventure sur les eaux turquoises du lac de Neuchâtel, ses bancs de sable et sa réserve naturelle préservée.", "Begeben Sie sich auf ein Abenteuer in den türkisfarbenen Gewässern des Neuenburgersees, seinen Sandbänken und seinem unberührten Naturschutzgebiet."),
        ('5 avis vérifiés', '5 verifizierte Bewertungen'),
        ('Propriétaire vérifié', 'Verifizierter Eigentümer'),
        ('Réserver maintenant', 'Jetzt buchen'),
        ('Découvrir le bateau', 'Das Boot entdecken'),
        ('>Longueur<', '>Länge<'),
        ('Personnes max', 'Max Personen'),
        ('Lits doubles', 'Doppelbetten'),
        ('Note · 5 avis', 'Bewertung · 5 Bewertungen'),
        ('Nuitées port Cheyres', 'Übernachtungen Hafen Cheyres'),
        ('>Le voilier<', '>Das Segelboot<'),
        ("Le Maxus 21 est un voilier habitable de 6.5 m, conçu par l'architecte naval Jacek Daszkiewicz et produit par le chantier polonais Northman. Gréé en sloop fractionné avec génois sur enrouleur, grand-voile lattée avec lazy-jack et gennaker, il offre un excellent compromis entre performance et facilité de manœuvre. Sa quille relevable (tirant d'eau de 0.35 à 1.45 m) permet d'accéder aux zones peu profondes et aux plages du lac de Neuchâtel. Le cockpit spacieux accueille confortablement 4 personnes, et la cabine équipée — frigo 12V, réchaud gaz, vaisselle, 2 lits doubles — permet de séjourner plusieurs nuits à bord en autonomie complète. Idéal pour les débutants avec permis comme pour les skippers expérimentés, en solo, en couple ou en famille.", "Die Maxus 21 ist ein 6,5 m langes Segelboot, entworfen vom Schiffsarchitekten Jacek Daszkiewicz und hergestellt von der polnischen Werft Northman. Getakelt als fraktionierte Slup mit Rollgenua, durchgelattetem Großsegel mit Lazy-Jack und Gennaker, bietet es einen hervorragenden Kompromiss zwischen Leistung und einfacher Handhabung. Sein Hubkiel (Tiefgang von 0,35 bis 1,45 m) ermöglicht den Zugang zu flachen Gebieten und den Stränden des Neuenburgersees. Das geräumige Cockpit bietet bequem Platz für 4 Personen, und die ausgestattete Kabine — 12V Kühlschrank, Gasherd, Geschirr, 2 Doppelbetten — ermöglicht mehrere Nächte an Bord bei völliger Autonomie. Ideal für Anfänger mit Führerschein sowie für erfahrene Skipper, allein, zu zweit oder mit der Familie."),
        ('Équipements et caractéristiques', 'Ausstattung und Eigenschaften'),
        ('Performances', 'Leistung'),
        ('Grand-voile 14m², Génois 9m², Gennaker 23m²', 'Großsegel 14m², Genua 9m², Gennaker 23m²'),
        ('Moteur hors-bord 5cv 4 temps', '5PS 4-Takt Außenbordmotor'),
        ('Confort à bord', 'Komfort an Bord'),
        ('2 lits doubles (avant et arrière) pour 4 personnes', '2 Doppelbetten (vorne und hinten) für 4 Personen'),
        ('Réchaud gaz, frigo 12V, vaisselle complète', 'Gasherd, 12V Kühlschrank, komplettes Geschirr'),
        ('Toilettes chimiques', 'Chemische Toiletten'),
        ('Pris USB, éclairage LED', 'USB-Anschlüsse, LED-Beleuchtung'),
        ('Sécurité', 'Sicherheit'),
        ('Armement de sécurité complet pour 4 personnes', 'Komplette Sicherheitsausrüstung für 4 Personen'),
        ('Bouées, gilets, fusées, extincteur', 'Bojen, Schwimmwesten, Leuchtraketen, Feuerlöscher'),
        ('>Navigation<', '>Navigation<'),
        ('Tableau électrique, loch, speedo, sondeur, compas', 'Elektrische Schalttafel, Logge, Tacho, Echolot, Kompass'),
        ('Cartes nautiques du lac de Neuchâtel', 'Seekarten des Neuenburgersees'),
        ('Tarifs de <em style="color:var(--lake)">location</em>', 'Miet<em style="color:var(--lake)">preise</em>'),
        ("Profitez d'un tarif dégressif dès le 2ème jour. Inclus : assurance casco complète et place d'amarrage à Cheyres.", "Profitieren Sie ab dem 2. Tag von einem degressiven Tarif. Inbegriffen: Vollkaskoversicherung und Liegeplatz in Cheyres."),
        ("Basse saison", "Nebensaison"),
        ("1 avr - 15 juin / 16 sept - 31 oct", "1. Apr - 15. Jun / 16. Sep - 31. Okt"),
        ("Haute saison", "Hochsaison"),
        ("16 juin - 15 sept", "16. Jun - 15. Sep"),
        ("Réserver ces dates", "Diese Daten buchen"),
        ("Nos options <em>disponibles</em>", "Unsere <em>verfügbaren</em> Optionen"),
        ("Personnalisez votre location avec nos options.", "Personalisieren Sie Ihre Miete mit unseren Optionen."),
        ("Moteur électrique", "Elektromotor"),
        ("Moteur Torqeedo Travel 1103 CS silencieux, écologique et performant.", "Torqeedo Travel 1103 CS Motor, leise, umweltfreundlich und leistungsstark."),
        ("Paddle Board", "Paddle Board"),
        ("SUP gonflable pour explorer les plages et bas-fonds.", "Aufblasbares SUP zur Erkundung von Stränden und Untiefen."),
        ("Nuit au port de Cheyres", "Nacht im Hafen von Cheyres"),
        ("Dormez à bord la veille de votre départ, accès aux sanitaires du port inclus.", "Schlafen Sie am Vorabend Ihrer Abreise an Bord, Zugang zu den Hafen-Sanitäranlagen inbegriffen."),
        (">Nettoyage<", ">Reinigung<"),
        ("Nettoyage complet intérieur et extérieur après votre location.", "Komplette Innen- und Außenreinigung nach Ihrer Miete."),
        ("Faites vous <em>accompagner</em>", "Lassen Sie sich <em>begleiten</em>"),
        ("Vous n'avez pas le permis voile marin ? Aucun problème. Avec le Pass Skipper, un skipper expérimenté vous accompagnera pour vous guider lors de votre sortie.", "Sie haben keinen Segelschein? Kein Problem. Mit dem Skipper-Pass begleitet Sie ein erfahrener Skipper, um Sie bei Ihrem Ausflug zu führen."),
        ("Jusqu'à 3 personnes maximum", "Bis zu 3 Personen maximal"),
        ("Journée de 9h à 17h : +150 CHF", "Tag von 9 bis 17 Uhr: +150 CHF"),
        ("Information de <em>location</em>", "Miet<em>informationen</em>"),
        ("Tout ce qu'il faut savoir avant de larguer les amarres.", "Alles, was Sie wissen müssen, bevor Sie die Leinen losmachen."),
        ("Conditions requises", "Anforderungen"),
        ("Permis voile (catégorie D) obligatoire suisse", "Schweizer Segelschein (Kategorie D) obligatorisch"),
        ("Âge minimum : 25 ans", "Mindestalter: 25 Jahre"),
        ("Caution de 1000 CHF", "Kaution von 1000 CHF"),
        (">Horaires<", ">Fahrpläne<"),
        ("Prise en charge dès 9h00", "Übernahme ab 9:00 Uhr"),
        ("Retour jusqu'à 17h00", "Rückgabe bis 17:00 Uhr"),
        ("Briefing de 30 min au départ", "30-minütiges Briefing vor der Abfahrt"),
        ("Inclus dans le prix", "Im Preis inbegriffen"),
        ("Amarrage au port de Cheyres", "Liegeplatz im Hafen von Cheyres"),
        ("Assurance casco complète (franchise 1000 CHF)", "Vollkaskoversicherung (1000 CHF Selbstbehalt)"),
        ("Ceinture de sauvetage automatiques", "Automatische Rettungswesten"),
        ("Équipement de sécurité complet", "Komplette Sicherheitsausrüstung"),
        ("Vaisselle et matériel de cuisine", "Geschirr und Küchenutensilien"),
        ("Taxe de séjour", "Kurtaxe"),
        ("À prévoir", "Mitzubringen"),
        ("Sac de couchage et oreiller", "Schlafsack und Kissen"),
        ("Chaussures à semelles claires et propres", "Schuhe mit sauberen und hellen Sohlen"),
        ("Crème solaire respectueuse de l'environnement", "Umweltfreundliche Sonnencreme"),
        ("Vêtements de pluie / adaptés à la météo", "Regenkleidung / wettergerechte Kleidung"),
        ("Vos affaires personnelles dans un sac souple idéalement", "Ihre persönlichen Gegenstände idealerweise in einer weichen Tasche"),
        ('Le lac de Neuchâtel, <em style="color:var(--lake)">votre terrain de jeu</em>', 'Neuenburgersee, <em style="color:var(--lake)">Ihr Spielplatz</em>'),
        ("Au départ du charmant port de Cheyres, découvrez la Rive Sud et sa réserve naturelle préservée. Naviguez jusqu'à Estavayer-le-Lac, Yvonand, ou traversez vers Neuchâtel et Grandson. Les plages de sable, les eaux turquoises et les paysages jurassiens vous offrent un cadre de navigation exceptionnel.", "Ausgehend vom charmanten Hafen Cheyres, entdecken Sie das Südufer und sein unberührtes Naturschutzgebiet. Segeln Sie nach Estavayer-le-Lac, Yvonand oder überqueren Sie den See nach Neuchâtel und Grandson. Die Sandstrände, das türkisfarbene Wasser und die Jurahänge bieten Ihnen eine außergewöhnliche Segelumgebung."),
        ("Avis de nos <em>navigateurs</em>", "Bewertungen unserer <em>Segler</em>"),
        ("Laisser un avis", "Bewertung hinterlassen"),
        ("Super journée", "Toller Tag"),
        ("Nous avons passé une journée magnifique sur le Maxus 21. Le bateau est très bien entretenu, facile à manœuvrer et parfait pour une sortie familiale. L'accueil au port de Cheyres était très pro et les conseils de navigation précieux.", "Wir haben einen herrlichen Tag auf der Maxus 21 verbracht. Das Boot ist sehr gepflegt, einfach zu manövrieren und perfekt für einen Familienausflug. Der Empfang im Hafen von Cheyres war sehr professionell und die Navigationshinweise von unschätzbarem Wert."),
        ("Week-end parfait", "Perfektes Wochenende"),
        ("Première expérience de nuit sur le lac de Neuchâtel. La cabine est étonnamment spacieuse pour la taille du bateau. Le frigo et le réchaud fonctionnent parfaitement. Réveil au mouillage devant la réserve naturelle : magique !", "Erstes Übernachtungserlebnis auf dem Neuenburgersee. Die Kabine ist für die Größe des Bootes erstaunlich geräumig. Kühlschrank und Herd funktionieren einwandfrei. Aufwachen vor Anker vor dem Naturschutzgebiet: magisch!"),
        ("Idéal pour se remettre à la voile", "Ideal für den Wiedereinstieg ins Segeln"),
        ("N'ayant pas navigué depuis quelques années, le Maxus 21 était le choix parfait. Rassurant, réactif et très fun sous gennaker. Merci pour le briefing détaillé avant le départ.", "Da ich einige Jahre nicht mehr gesegelt war, war die Maxus 21 die perfekte Wahl. Beruhigend, reaktionsschnell und sehr spaßig unter Gennaker. Vielen Dank für das detaillierte Briefing vor dem Start."),
        ('Port de <em>Cheyres</em>', 'Hafen von <em>Cheyres</em>'),
        ("Notre voilier est amarré au port de Cheyres, sur la rive sud du lac de Neuchâtel. Un point de départ idéal !", "Unser Segelboot liegt im Hafen von Cheyres, am Südufer des Neuenburgersees. Ein idealer Ausgangspunkt!"),
        (">Cheyres<", ">Cheyres<"),
        ("Gare CFF à 10 minutes à pied.", "SBB-Bahnhof 10 Gehminuten entfernt."),
        ("Parking gratuit à disposition au nord.", "Kostenlose Parkplätze im Norden verfügbar."),
        ("Sanitaires, douches, restaurants.", "Sanitäre Anlagen, Duschen, Restaurants."),
        ('Prêt à <em>embarquer</em> ?', 'Bereit zum <em>Einsteigen</em>?'),
        ("Remplissez le formulaire ci-dessous avec vos dates souhaitées. Nous vous répondrons sous 24h avec une confirmation et les instructions pour le paiement de l'acompte.", "Füllen Sie das untenstehende Formular mit Ihren Wunschdaten aus. Wir antworten Ihnen innerhalb von 24h mit einer Bestätigung und Anweisungen für die Anzahlung."),
        ("Votre nom", "Ihr Name"),
        ("Votre e-mail", "Ihre E-Mail"),
        ("Numéro de téléphone", "Telefonnummer"),
        ("Jour de départ", "Abreisetag"),
        ("Jour de retour", "Rückkehrtag"),
        ("Option de location", "Mietoption"),
        ("Je choisis mes options", "Ich wähle meine Optionen"),
        (">Aucune<", ">Keine<"),
        ("Message ou question éventuelle", "Nachricht oder mögliche Frage"),
        ("Êtes vous prêt pour une confirmation ?", "Sind Sie bereit für eine Bestätigung?"),
        (">Oui<", ">Ja<"),
        ("Je l'envoi", "Senden"),
        ("Location en demande :", "Miete auf Anfrage:"),
        ("Votre propriétaire", "Ihr Eigentümer"),
        ("Je m'appelle Grégory, naviguant sur les lacs de Neuchâtel et Bienne depuis toujours. C'est avec plaisir de pouvoir partager mon bateau aujourd'hui.", "Mein Name ist Grégory, ich segle schon immer auf dem Neuenburger- und Bielersee. Es ist mir eine Freude, heute mein Boot teilen zu können."),
        ("Voilier situé au", "Segelboot befindet sich in"),
        (">Port de Cheyres<", ">Hafen von Cheyres<"),
        ("Rte du Port", "Hafenstrasse"),
        ("1468 Cheyres", "1468 Cheyres"),
        (">Suisse<", ">Schweiz<"),
        ("Contact & Suivi", "Kontakt & Folgen"),
        ("Partenariat", "Partnerschaft"),
        (">Conditions<", ">Bedingungen<"),
        ("Conditions de location", "Mietbedingungen"),
        ("Mentions légales", "Impressum"),
        ("Tous droits réservés.", "Alle Rechte vorbehalten.")
    ]

    de_content = fr
    for old, new in de_replacements:
        de_content = de_content.replace(old, new)

    de_content = de_content.replace('lang-active">FR</a> <a href="/de/">DE</a> <a href="/en/">EN',
                                  '">FR</a> <a href="/de/" class="lang-active">DE</a> <a href="/en/">EN')
    de_content = de_content.replace('<html lang="fr">', '<html lang="de">')
    de_content = de_content.replace('<title>Location de Voilier au lac de Neuchâtel | Port de Cheyres</title>', '<title>Segeln Neuenburgersee | Segelboot Mieten | Hafen von Cheyres</title>')
    de_content = de_content.replace('value="Nouvelle demande de réservation (FR)"', 'value="Neue Buchungsanfrage (DE)"')

    with open('site/de/index.html', 'w', encoding='utf-8') as f:
        f.write(de_content)

if __name__ == "__main__":
    main()
